export interface CountryCodeOption {
  code: string;
  dialCode: string;
  name: string;
  phoneLength: number; // Expected number of digits after country code
}

export const ALL_COUNTRY_CODES: CountryCodeOption[] = [
  { code: "AF", dialCode: "+93", name: "Afghanistan", phoneLength: 9 },
  { code: "AL", dialCode: "+355", name: "Albania", phoneLength: 9 },
  { code: "DZ", dialCode: "+213", name: "Algeria", phoneLength: 9 },
  { code: "AD", dialCode: "+376", name: "Andorra", phoneLength: 6 },
  { code: "AO", dialCode: "+244", name: "Angola", phoneLength: 9 },
  { code: "AG", dialCode: "+1", name: "Antigua and Barbuda", phoneLength: 10 },
  { code: "AR", dialCode: "+54", name: "Argentina", phoneLength: 10 },
  { code: "AM", dialCode: "+374", name: "Armenia", phoneLength: 8 },
  { code: "AU", dialCode: "+61", name: "Australia", phoneLength: 9 },
  { code: "AT", dialCode: "+43", name: "Austria", phoneLength: 10 },
  { code: "AZ", dialCode: "+994", name: "Azerbaijan", phoneLength: 9 },
  { code: "BS", dialCode: "+1", name: "Bahamas", phoneLength: 10 },
  { code: "BH", dialCode: "+973", name: "Bahrain", phoneLength: 8 },
  { code: "BD", dialCode: "+880", name: "Bangladesh", phoneLength: 10 },
  { code: "BB", dialCode: "+1", name: "Barbados", phoneLength: 10 },
  { code: "BY", dialCode: "+375", name: "Belarus", phoneLength: 9 },
  { code: "BE", dialCode: "+32", name: "Belgium", phoneLength: 9 },
  { code: "BZ", dialCode: "+501", name: "Belize", phoneLength: 7 },
  { code: "BJ", dialCode: "+229", name: "Benin", phoneLength: 8 },
  { code: "BT", dialCode: "+975", name: "Bhutan", phoneLength: 8 },
  { code: "BO", dialCode: "+591", name: "Bolivia", phoneLength: 8 },
  { code: "BA", dialCode: "+387", name: "Bosnia and Herzegovina", phoneLength: 8 },
  { code: "BW", dialCode: "+267", name: "Botswana", phoneLength: 8 },
  { code: "BR", dialCode: "+55", name: "Brazil", phoneLength: 11 },
  { code: "BN", dialCode: "+673", name: "Brunei", phoneLength: 7 },
  { code: "BG", dialCode: "+359", name: "Bulgaria", phoneLength: 9 },
  { code: "BF", dialCode: "+226", name: "Burkina Faso", phoneLength: 8 },
  { code: "BI", dialCode: "+257", name: "Burundi", phoneLength: 8 },
  { code: "KH", dialCode: "+855", name: "Cambodia", phoneLength: 9 },
  { code: "CM", dialCode: "+237", name: "Cameroon", phoneLength: 9 },
  { code: "CA", dialCode: "+1", name: "Canada", phoneLength: 10 },
  { code: "CV", dialCode: "+238", name: "Cape Verde", phoneLength: 7 },
  { code: "CF", dialCode: "+236", name: "Central African Republic", phoneLength: 8 },
  { code: "TD", dialCode: "+235", name: "Chad", phoneLength: 8 },
  { code: "CL", dialCode: "+56", name: "Chile", phoneLength: 9 },
  { code: "CN", dialCode: "+86", name: "China", phoneLength: 11 },
  { code: "CO", dialCode: "+57", name: "Colombia", phoneLength: 10 },
  { code: "KM", dialCode: "+269", name: "Comoros", phoneLength: 7 },
  { code: "CG", dialCode: "+242", name: "Congo", phoneLength: 9 },
  { code: "CR", dialCode: "+506", name: "Costa Rica", phoneLength: 8 },
  { code: "HR", dialCode: "+385", name: "Croatia", phoneLength: 9 },
  { code: "CU", dialCode: "+53", name: "Cuba", phoneLength: 8 },
  { code: "CY", dialCode: "+357", name: "Cyprus", phoneLength: 8 },
  { code: "CZ", dialCode: "+420", name: "Czech Republic", phoneLength: 9 },
  { code: "DK", dialCode: "+45", name: "Denmark", phoneLength: 8 },
  { code: "DJ", dialCode: "+253", name: "Djibouti", phoneLength: 8 },
  { code: "DM", dialCode: "+1", name: "Dominica", phoneLength: 10 },
  { code: "DO", dialCode: "+1", name: "Dominican Republic", phoneLength: 10 },
  { code: "EC", dialCode: "+593", name: "Ecuador", phoneLength: 9 },
  { code: "EG", dialCode: "+20", name: "Egypt", phoneLength: 10 },
  { code: "SV", dialCode: "+503", name: "El Salvador", phoneLength: 8 },
  { code: "GQ", dialCode: "+240", name: "Equatorial Guinea", phoneLength: 9 },
  { code: "ER", dialCode: "+291", name: "Eritrea", phoneLength: 7 },
  { code: "EE", dialCode: "+372", name: "Estonia", phoneLength: 8 },
  { code: "ET", dialCode: "+251", name: "Ethiopia", phoneLength: 9 },
  { code: "FJ", dialCode: "+679", name: "Fiji", phoneLength: 7 },
  { code: "FI", dialCode: "+358", name: "Finland", phoneLength: 10 },
  { code: "FR", dialCode: "+33", name: "France", phoneLength: 9 },
  { code: "GA", dialCode: "+241", name: "Gabon", phoneLength: 8 },
  { code: "GM", dialCode: "+220", name: "Gambia", phoneLength: 7 },
  { code: "GE", dialCode: "+995", name: "Georgia", phoneLength: 9 },
  { code: "DE", dialCode: "+49", name: "Germany", phoneLength: 10 },
  { code: "GH", dialCode: "+233", name: "Ghana", phoneLength: 9 },
  { code: "GR", dialCode: "+30", name: "Greece", phoneLength: 10 },
  { code: "GD", dialCode: "+1", name: "Grenada", phoneLength: 10 },
  { code: "GT", dialCode: "+502", name: "Guatemala", phoneLength: 8 },
  { code: "GN", dialCode: "+224", name: "Guinea", phoneLength: 9 },
  { code: "GW", dialCode: "+245", name: "Guinea-Bissau", phoneLength: 7 },
  { code: "GY", dialCode: "+592", name: "Guyana", phoneLength: 7 },
  { code: "HT", dialCode: "+509", name: "Haiti", phoneLength: 8 },
  { code: "HN", dialCode: "+504", name: "Honduras", phoneLength: 8 },
  { code: "HK", dialCode: "+852", name: "Hong Kong", phoneLength: 8 },
  { code: "HU", dialCode: "+36", name: "Hungary", phoneLength: 9 },
  { code: "IS", dialCode: "+354", name: "Iceland", phoneLength: 7 },
  { code: "IN", dialCode: "+91", name: "India", phoneLength: 10 },
  { code: "ID", dialCode: "+62", name: "Indonesia", phoneLength: 10 },
  { code: "IR", dialCode: "+98", name: "Iran", phoneLength: 10 },
  { code: "IQ", dialCode: "+964", name: "Iraq", phoneLength: 10 },
  { code: "IE", dialCode: "+353", name: "Ireland", phoneLength: 9 },
  { code: "IL", dialCode: "+972", name: "Israel", phoneLength: 9 },
  { code: "IT", dialCode: "+39", name: "Italy", phoneLength: 10 },
  { code: "JM", dialCode: "+1", name: "Jamaica", phoneLength: 10 },
  { code: "JP", dialCode: "+81", name: "Japan", phoneLength: 10 },
  { code: "JO", dialCode: "+962", name: "Jordan", phoneLength: 9 },
  { code: "KZ", dialCode: "+7", name: "Kazakhstan", phoneLength: 10 },
  { code: "KE", dialCode: "+254", name: "Kenya", phoneLength: 9 },
  { code: "KI", dialCode: "+686", name: "Kiribati", phoneLength: 8 },
  { code: "KW", dialCode: "+965", name: "Kuwait", phoneLength: 8 },
  { code: "KG", dialCode: "+996", name: "Kyrgyzstan", phoneLength: 9 },
  { code: "LA", dialCode: "+856", name: "Laos", phoneLength: 10 },
  { code: "LV", dialCode: "+371", name: "Latvia", phoneLength: 8 },
  { code: "LB", dialCode: "+961", name: "Lebanon", phoneLength: 8 },
  { code: "LS", dialCode: "+266", name: "Lesotho", phoneLength: 8 },
  { code: "LR", dialCode: "+231", name: "Liberia", phoneLength: 8 },
  { code: "LY", dialCode: "+218", name: "Libya", phoneLength: 9 },
  { code: "LI", dialCode: "+423", name: "Liechtenstein", phoneLength: 7 },
  { code: "LT", dialCode: "+370", name: "Lithuania", phoneLength: 8 },
  { code: "LU", dialCode: "+352", name: "Luxembourg", phoneLength: 9 },
  { code: "MO", dialCode: "+853", name: "Macao", phoneLength: 8 },
  { code: "MG", dialCode: "+261", name: "Madagascar", phoneLength: 9 },
  { code: "MW", dialCode: "+265", name: "Malawi", phoneLength: 9 },
  { code: "MY", dialCode: "+60", name: "Malaysia", phoneLength: 9 },
  { code: "MV", dialCode: "+960", name: "Maldives", phoneLength: 7 },
  { code: "ML", dialCode: "+223", name: "Mali", phoneLength: 8 },
  { code: "MT", dialCode: "+356", name: "Malta", phoneLength: 8 },
  { code: "MH", dialCode: "+692", name: "Marshall Islands", phoneLength: 7 },
  { code: "MR", dialCode: "+222", name: "Mauritania", phoneLength: 8 },
  { code: "MU", dialCode: "+230", name: "Mauritius", phoneLength: 8 },
  { code: "MX", dialCode: "+52", name: "Mexico", phoneLength: 10 },
  { code: "FM", dialCode: "+691", name: "Micronesia", phoneLength: 7 },
  { code: "MD", dialCode: "+373", name: "Moldova", phoneLength: 8 },
  { code: "MC", dialCode: "+377", name: "Monaco", phoneLength: 8 },
  { code: "MN", dialCode: "+976", name: "Mongolia", phoneLength: 8 },
  { code: "ME", dialCode: "+382", name: "Montenegro", phoneLength: 8 },
  { code: "MA", dialCode: "+212", name: "Morocco", phoneLength: 9 },
  { code: "MZ", dialCode: "+258", name: "Mozambique", phoneLength: 9 },
  { code: "MM", dialCode: "+95", name: "Myanmar", phoneLength: 9 },
  { code: "NA", dialCode: "+264", name: "Namibia", phoneLength: 9 },
  { code: "NR", dialCode: "+674", name: "Nauru", phoneLength: 7 },
  { code: "NP", dialCode: "+977", name: "Nepal", phoneLength: 10 },
  { code: "NL", dialCode: "+31", name: "Netherlands", phoneLength: 9 },
  { code: "NZ", dialCode: "+64", name: "New Zealand", phoneLength: 9 },
  { code: "NI", dialCode: "+505", name: "Nicaragua", phoneLength: 8 },
  { code: "NE", dialCode: "+227", name: "Niger", phoneLength: 8 },
  { code: "NG", dialCode: "+234", name: "Nigeria", phoneLength: 10 },
  { code: "KP", dialCode: "+850", name: "North Korea", phoneLength: 10 },
  { code: "MK", dialCode: "+389", name: "North Macedonia", phoneLength: 8 },
  { code: "NO", dialCode: "+47", name: "Norway", phoneLength: 8 },
  { code: "OM", dialCode: "+968", name: "Oman", phoneLength: 8 },
  { code: "PK", dialCode: "+92", name: "Pakistan", phoneLength: 10 },
  { code: "PW", dialCode: "+680", name: "Palau", phoneLength: 7 },
  { code: "PA", dialCode: "+507", name: "Panama", phoneLength: 8 },
  { code: "PG", dialCode: "+675", name: "Papua New Guinea", phoneLength: 8 },
  { code: "PY", dialCode: "+595", name: "Paraguay", phoneLength: 9 },
  { code: "PE", dialCode: "+51", name: "Peru", phoneLength: 9 },
  { code: "PH", dialCode: "+63", name: "Philippines", phoneLength: 10 },
  { code: "PL", dialCode: "+48", name: "Poland", phoneLength: 9 },
  { code: "PT", dialCode: "+351", name: "Portugal", phoneLength: 9 },
  { code: "QA", dialCode: "+974", name: "Qatar", phoneLength: 8 },
  { code: "RO", dialCode: "+40", name: "Romania", phoneLength: 10 },
  { code: "RU", dialCode: "+7", name: "Russia", phoneLength: 10 },
  { code: "RW", dialCode: "+250", name: "Rwanda", phoneLength: 9 },
  { code: "KN", dialCode: "+1", name: "Saint Kitts and Nevis", phoneLength: 10 },
  { code: "LC", dialCode: "+1", name: "Saint Lucia", phoneLength: 10 },
  { code: "VC", dialCode: "+1", name: "Saint Vincent and the Grenadines", phoneLength: 10 },
  { code: "WS", dialCode: "+685", name: "Samoa", phoneLength: 7 },
  { code: "SM", dialCode: "+378", name: "San Marino", phoneLength: 8 },
  { code: "ST", dialCode: "+239", name: "Sao Tome and Principe", phoneLength: 7 },
  { code: "SA", dialCode: "+966", name: "Saudi Arabia", phoneLength: 9 },
  { code: "SN", dialCode: "+221", name: "Senegal", phoneLength: 9 },
  { code: "RS", dialCode: "+381", name: "Serbia", phoneLength: 9 },
  { code: "SC", dialCode: "+248", name: "Seychelles", phoneLength: 7 },
  { code: "SL", dialCode: "+232", name: "Sierra Leone", phoneLength: 8 },
  { code: "SG", dialCode: "+65", name: "Singapore", phoneLength: 8 },
  { code: "SK", dialCode: "+421", name: "Slovakia", phoneLength: 9 },
  { code: "SI", dialCode: "+386", name: "Slovenia", phoneLength: 9 },
  { code: "SB", dialCode: "+677", name: "Solomon Islands", phoneLength: 7 },
  { code: "SO", dialCode: "+252", name: "Somalia", phoneLength: 8 },
  { code: "ZA", dialCode: "+27", name: "South Africa", phoneLength: 9 },
  { code: "KR", dialCode: "+82", name: "South Korea", phoneLength: 10 },
  { code: "SS", dialCode: "+211", name: "South Sudan", phoneLength: 9 },
  { code: "ES", dialCode: "+34", name: "Spain", phoneLength: 9 },
  { code: "LK", dialCode: "+94", name: "Sri Lanka", phoneLength: 9 },
  { code: "SD", dialCode: "+249", name: "Sudan", phoneLength: 9 },
  { code: "SR", dialCode: "+597", name: "Suriname", phoneLength: 7 },
  { code: "SZ", dialCode: "+268", name: "Eswatini", phoneLength: 8 },
  { code: "SE", dialCode: "+46", name: "Sweden", phoneLength: 9 },
  { code: "CH", dialCode: "+41", name: "Switzerland", phoneLength: 9 },
  { code: "SY", dialCode: "+963", name: "Syria", phoneLength: 9 },
  { code: "TW", dialCode: "+886", name: "Taiwan", phoneLength: 9 },
  { code: "TJ", dialCode: "+992", name: "Tajikistan", phoneLength: 9 },
  { code: "TZ", dialCode: "+255", name: "Tanzania", phoneLength: 9 },
  { code: "TH", dialCode: "+66", name: "Thailand", phoneLength: 9 },
  { code: "TL", dialCode: "+670", name: "Timor-Leste", phoneLength: 8 },
  { code: "TG", dialCode: "+228", name: "Togo", phoneLength: 8 },
  { code: "TO", dialCode: "+676", name: "Tonga", phoneLength: 7 },
  { code: "TT", dialCode: "+1", name: "Trinidad and Tobago", phoneLength: 10 },
  { code: "TN", dialCode: "+216", name: "Tunisia", phoneLength: 8 },
  { code: "TR", dialCode: "+90", name: "Turkey", phoneLength: 10 },
  { code: "TM", dialCode: "+993", name: "Turkmenistan", phoneLength: 8 },
  { code: "TV", dialCode: "+688", name: "Tuvalu", phoneLength: 7 },
  { code: "UG", dialCode: "+256", name: "Uganda", phoneLength: 9 },
  { code: "UA", dialCode: "+380", name: "Ukraine", phoneLength: 9 },
  { code: "AE", dialCode: "+971", name: "United Arab Emirates", phoneLength: 9 },
  { code: "GB", dialCode: "+44", name: "United Kingdom", phoneLength: 10 },
  { code: "US", dialCode: "+1", name: "United States", phoneLength: 10 },
  { code: "UY", dialCode: "+598", name: "Uruguay", phoneLength: 8 },
  { code: "UZ", dialCode: "+998", name: "Uzbekistan", phoneLength: 9 },
  { code: "VU", dialCode: "+678", name: "Vanuatu", phoneLength: 7 },
  { code: "VA", dialCode: "+379", name: "Vatican City", phoneLength: 10 },
  { code: "VE", dialCode: "+58", name: "Venezuela", phoneLength: 10 },
  { code: "VN", dialCode: "+84", name: "Vietnam", phoneLength: 9 },
  { code: "YE", dialCode: "+967", name: "Yemen", phoneLength: 9 },
  { code: "ZM", dialCode: "+260", name: "Zambia", phoneLength: 9 },
  { code: "ZW", dialCode: "+263", name: "Zimbabwe", phoneLength: 9 },
];

export function formatPhoneCodeLabel(option: CountryCodeOption): string {
  return `${option.dialCode} (${option.name})`;
}

export function countryCodeToFlag(code: string): string {
  return code
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}
