import type { CandmainLandingContent } from './types'

export const candmainLandingEn: CandmainLandingContent = {
  dateLocale: 'en-US',
  commandCenter: {
    tag: 'Platform Outcomes',
    title: 'Trusted Outcomes.',
    titleAccent: 'Measurable Career Growth.',
    subtitle:
      'Join an AI-based platform designed to help candidates get discovered, secure interviews, and accelerate career growth through AI-powered matching and recruiter visibility.',
    liveFeed: 'Live Feed',
    ticker: [
      'Recruiter viewed profile - Operations Manager role',
      'Interview scheduled - Finance Analyst opening',
      'Resume shortlisted - Healthcare Coordinator role',
      'Profile quality improved to 94%',
      'New certification verified - Project Management',
      'Skill check completed - Communication and reporting',
      'Application moved to hiring manager review',
      'New role match found with 92% fit',
      'Offer activity detected - Customer Success role',
    ],
    stats: [
      { id: 'matches', label: 'AI Job Matches', value: '42', status: 'live', statusLabel: 'live', trend: 'Roles aligned to your profile on Explore Jobs.' },
      { id: 'applications', label: 'Active Applications', value: '18', status: 'active', statusLabel: 'active', trend: 'Tracked in Applications with live status updates.' },
      { id: 'profile', label: 'Profile Completion', value: '94%', status: 'excellent', statusLabel: 'excellent', trend: 'Complete your candidate profile for better recruiter visibility.' },
      { id: 'resume', label: 'Resume Builder Score', value: '88', status: 'growing', statusLabel: 'growing', trend: 'Improve ATS readiness with LMS Resume Builder.' },
      { id: 'interviews', label: 'Interview Prep Sessions', value: '12', status: 'excellent', statusLabel: 'excellent', trend: 'Mock interviews and question banks in LMS.' },
      { id: 'ats', label: 'ATS Check Pass Rate', value: '92%', status: 'excellent', statusLabel: 'excellent', trend: 'Scan your CV before applying to open roles.' },
      { id: 'courses', label: 'Learning Paths Started', value: '6', status: 'active', statusLabel: 'active', trend: 'Upskill with courses and career-path planning.' },
      { id: 'response', label: 'Recruiter Response Rate', value: '58%', status: 'growing', statusLabel: 'growing', trend: 'Stronger profiles get more responses from tenant recruiters.' },
    ],
  },
  activity: {
    tag: 'Always Moving',
    title: 'Live',
    titleAccent: 'Career Activity Stream',
    subtitle:
      'Every recruiter view, interview update, shortlist, role match, and skill signal is streamed live for candidates across tech, business, healthcare, finance, sales, design, operations, and more.',
    stats: [
      { label: 'Live Profile Views', value: '42' },
      { label: 'Role Matches Found', value: '12.5K+' },
      { label: 'Interview Updates', value: '8' },
    ],
    streamTitle: 'Activity Stream',
    latestUpdate: 'Latest update',
    feed: [
      { id: 1, type: 'metrics', typeLabel: 'metrics', message: 'Application moved to Interview — Full Stack Developer', time: 'now', status: 'success' },
      { id: 2, type: 'research', typeLabel: 'research', message: 'Recruiter viewed your profile — Product Manager role', time: '1m ago', status: 'success' },
      { id: 3, type: 'accessibility', typeLabel: 'accessibility', message: 'Resume tailored for job — Finance Analyst opening', time: '2m ago', status: 'success' },
      { id: 4, type: 'product', typeLabel: 'product', message: 'AI match score improved — better fit for Pune roles', time: '3m ago', status: 'success' },
      { id: 5, type: 'performance', typeLabel: 'performance', message: 'Pre-screen assessment completed — Operations role', time: '4m ago', status: 'success' },
      { id: 6, type: 'feedback', typeLabel: 'feedback', message: 'Mock interview finished — communication readiness up', time: '5m ago', status: 'success' },
      { id: 7, type: 'deploy', typeLabel: 'deploy', message: 'New job posted — React Developer (Remote)', time: '6m ago', status: 'success' },
      { id: 8, type: 'design', typeLabel: 'design', message: 'Profile synced from Phase 2 CRM pipeline', time: '7m ago', status: 'success' },
      { id: 9, type: 'report', typeLabel: 'report', message: 'Follow-up reminder — Sales Executive application', time: '8m ago', status: 'info' },
      { id: 10, type: 'metrics', typeLabel: 'metrics', message: 'Shortlisted — Customer Success role pool', time: '9m ago', status: 'info' },
      { id: 11, type: 'research', typeLabel: 'research', message: 'Hiring manager opened application — HR Business Partner', time: '10m ago', status: 'success' },
      { id: 12, type: 'performance', typeLabel: 'performance', message: 'Skill added to profile — Excel & business analysis', time: '11m ago', status: 'success' },
    ],
  },
  hiring: {
    tag: 'Hiring Intelligence',
    title: 'The Complete',
    titleAccent: 'Hiring Process Hierarchy',
    subtitle:
      'See how candidates move from application to offer across tech, business, finance, healthcare, sales, operations, design, and more.',
    funnelTitle: 'Live Hiring Funnel',
    funnelUpdated: 'Real-time candidate progression across all 6 stages - Updated',
    liveData: 'Live Data',
    stageLabel: 'Stage',
    liveSuffix: 'live now',
    passPrefix: 'Pass',
    totalPool: 'Total applicant pool',
    refreshNote: '% and live counts refresh in real time',
    stages: [
      { id: 'application', step: 1, title: 'Resume Screening', subtitle: 'AI checks resume fit, keywords, and role match.', duration: '24–72 hrs', passRate: '~15%', companies: ['Resume Scan', 'Role Match', 'Clear Fit'], color: '#2563EB', bg: 'rgba(37,99,235,0.06)', border: 'rgba(37,99,235,0.18)', liveCount: 12500 },
      { id: 'recruiter', step: 2, title: 'Recruiter Screen', subtitle: 'Recruiter checks interest, salary range, and availability.', duration: '30–45 min', passRate: '~60%', companies: ['Intent', 'Salary Fit', 'Availability'], color: '#0EA5E9', bg: 'rgba(14,165,233,0.08)', border: 'rgba(14,165,233,0.24)', liveCount: 1875 },
      { id: 'technical', step: 3, title: 'Skill Assessment', subtitle: 'Skills are tested through tasks, case work, or portfolio review.', duration: '1–3 hrs', passRate: '~40%', companies: ['Skill Test', 'Case Study', 'Portfolio'], color: '#7C3AED', bg: 'rgba(124,58,237,0.08)', border: 'rgba(124,58,237,0.24)', liveCount: 750 },
      { id: 'hiring-manager', step: 4, title: 'Manager Interview', subtitle: 'Manager reviews experience, team fit, and business impact.', duration: '45–60 min', passRate: '~55%', companies: ['Impact', 'Team Fit', 'Leadership'], color: '#F97316', bg: 'rgba(249,115,22,0.08)', border: 'rgba(249,115,22,0.24)', liveCount: 412 },
      { id: 'panel', step: 5, title: 'Panel Interviews', subtitle: 'Final team rounds validate consistency and collaboration.', duration: '3–6 hrs', passRate: '~70%', companies: ['Team Loop', 'Culture Fit', 'Final Review'], color: '#EC4899', bg: 'rgba(236,72,153,0.08)', border: 'rgba(236,72,153,0.24)', liveCount: 289 },
      { id: 'offer', step: 6, title: 'Offer & Onboarding', subtitle: 'Offer, background check, negotiation, and joining steps.', duration: '1–2 weeks', passRate: '~85%', companies: ['Offer', 'BGV', 'Onboarding'], color: '#059669', bg: 'rgba(5,150,105,0.06)', border: 'rgba(5,150,105,0.18)', liveCount: 246 },
    ],
    banner: [
      { label: 'Avg. End-to-End Hire Time', value: '4–8 Weeks' },
      { label: 'Offers from 12.5K+ Applications', value: '~246 Offers' },
      { label: 'HR Yantra Interview Success Rate', value: '94%' },
      { label: 'Salary Uplift via Negotiation Tips', value: '+21% avg' },
    ],
  },
  impact: {
    tag: 'Career Outcomes',
    title: 'The',
    titleAccent: 'Career Growth Dashboard',
    subtitle:
      'Every application milestone, recruiter callback, match rating, and funnel conversion metric — tracked and updated in real-time.',
    metrics: [
      { label: 'Recruiter Views', detail: 'Live profile discovery' },
      { label: 'Active Jobs Sourced', detail: 'Open roles tracked now' },
      { label: 'Job Match Accuracy', detail: 'AI role-fit validation' },
      { label: 'Interview Rate', detail: 'Application to interview flow' },
    ],
    chartTitle: 'Hiring Funnel Trajectory',
    chartUpdated: 'Automated live view - updated',
    graphMeaning: 'What this graph means',
    latest: 'Latest',
    change: 'Change',
    liveReading: 'live reading',
    tabs: [
      { id: 'users', label: 'Recruiter Views', insight: 'How often recruiters are finding and opening candidate profiles.', plain: 'More views means stronger visibility in recruiter searches.' },
      { id: 'revenue', label: 'Active Openings', insight: 'How many open roles are being matched across the platform.', plain: 'More openings means more chances to find a relevant role.' },
      { id: 'adoption', label: 'Job Match Rate', insight: 'How closely candidate profiles match available jobs.', plain: 'Higher match rate means better role fit and less wasted applying.' },
      { id: 'conversion', label: 'Interview Rate', insight: 'How often matched candidates convert into interviews.', plain: 'Higher interview rate means the profile is getting real traction.' },
    ],
    format: { openings: 'openings', views: 'views' },
  },
  caseStudies: {
    tag: 'Platform Success Stories',
    title: 'Simple Outcomes.',
    titleAccent: 'Clear Career Progress.',
    subtitle:
      'See how HR Yantra helps candidates explore jobs, improve profiles, complete assessments, and track applications through the Phase 1 portal.',
    problem: 'Problem',
    checks: 'What HR Yantra Checks',
    helps: 'How It Helps',
    showLess: 'Show Less',
    outcome: 'Candidate Outcome',
    studies: [
      {
        id: 'explore-jobs', tag: 'Explore Jobs', title: 'Discover and Apply to Roles Posted on the Portal',
        challenge: 'Candidates bounce between job boards without knowing which openings are active, verified, and matched to their profile on HR Yantra.',
        research: 'The Explore Jobs page lists live tenant-posted roles with AI match hints, salary visibility, work mode, and one-click apply when your profile is ready.',
        strategy: 'Search by title and location, open job details, tailor your resume in LMS, and submit applications tracked in your dashboard.',
        results: [
          { metric: 'Live Jobs', value: '500+', detail: 'Open on portal' },
          { metric: 'Match Score', value: '91%', detail: 'Profile fit' },
          { metric: 'Apply Flow', value: '1-Click', detail: 'When profile ready' },
          { metric: 'Tracking', value: '100%', detail: 'In Applications' },
        ],
        color: '#28A8E1', bgColor: 'rgba(40,168,225,0.06)',
      },
      {
        id: 'profile-lms', tag: 'Profile & LMS', title: 'Build a Recruiter-Ready Profile and Resume',
        challenge: 'Incomplete profiles and generic CVs reduce visibility when recruiters search the Phase 1 candidate pool and Phase 2 CRM tenants.',
        research: 'HR Yantra combines Profile, Upload CV, ATS Check, and LMS Resume Builder so candidates improve keywords, skills, and formatting before applying.',
        strategy: 'Complete personal details, run ATS check, use AI resume editor, and sync improvements back to your portal candidate record.',
        results: [
          { metric: 'ATS Score', value: '92', detail: 'After optimization' },
          { metric: 'Profile', value: '94%', detail: 'Completion' },
          { metric: 'Skills', value: '24+', detail: 'Verified tags' },
          { metric: 'Time Saved', value: '8h', detail: 'Vs manual edits' },
        ],
        color: '#FC9620', bgColor: 'rgba(252,150,32,0.06)',
      },
      {
        id: 'applications-pipeline', tag: 'Applications', title: 'Track Every Application, Assessment, and Interview',
        challenge: 'Candidates lose track of screening tests, recruiter messages, and interview stages across multiple employer pipelines.',
        research: 'Applications and Candidate Dashboard show status timelines, pre-screen assessments, interview prep links, and placement progress from Phase 2 sync.',
        strategy: 'Monitor active applications, complete assessments from apply flow, and use LMS Interview Prep before recruiter rounds.',
        results: [
          { metric: 'Visibility', value: '96%', detail: 'Status clarity' },
          { metric: 'Assessments', value: 'Done', detail: 'In apply flow' },
          { metric: 'Interviews', value: '5', detail: 'Scheduled' },
          { metric: 'Response', value: '58%', detail: 'Recruiter replies' },
        ],
        color: '#10B981', bgColor: 'rgba(16,185,129,0.06)',
      },
    ],
  },
  skills: {
    tag: 'Live Hiring Intelligence',
    title: 'What Recruiters',
    titleAccent: 'Care About',
    subtitle:
      'Recruiters look at clear experience, relevant skills, communication, role fit, growth potential, and proof that a candidate can create value in any field.',
    footer:
      'Live updates: recruiter views, role matches, resume quality, profile ranking, interview readiness, certifications, salary benchmarks, and recruiter engagement across the platform.',
    nodes: {
      center: 'Candidate Evaluation Matrix',
      'product-strategy': 'Relevant Experience',
      'design-systems': 'Job Skills',
      'ux-research': 'Career Progression',
      frontend: 'Certifications',
      leadership: 'Resume Quality',
      ai: 'Role Alignment',
      analytics: 'Leadership Potential',
      accessibility: 'Communication',
      'systems-thinking': 'Problem Solving',
      growth: 'Business Impact',
    },
  },
  experience: {
    tag: 'Candidate Journey',
    title: 'Live Hiring',
    titleAccent: 'Pipeline',
    subtitle:
      'Track how a candidate moves from profile setup to recruiter discovery, interview readiness, and active offer-stage momentum.',
    stagesCount: 'Live evaluation stages',
    stagesHint: 'Stage 1 profile signal to Stage 4 hiring movement',
    steps: [
      { id: 'signup', company: 'WhatsApp Sign-In', role: 'Step 1: Join the Portal', period: 'Day 1', description: 'Sign in with WhatsApp, verify your number, and land on your candidate dashboard with personalized job recommendations.', highlights: ['Quick OTP login', 'Secure session', 'Dashboard access'], color: '#28A8E1' },
      { id: 'profile', company: 'Profile & CV Setup', role: 'Step 2: Complete Your Profile', period: 'Week 1', description: 'Add experience, education, skills, and upload your CV. Run ATS Check and improve your resume in LMS Resume Builder.', highlights: ['Profile 94% complete', 'ATS optimized', 'Skills tagged'], color: '#28A8DF' },
      { id: 'explore', company: 'Explore Jobs', role: 'Step 3: Search & Apply', period: 'Week 2', description: 'Browse live openings from agency tenants, filter by location and role type, and apply with tailored CVs and screening flows.', highlights: ['42 AI matches', 'Remote & hybrid roles', 'Tracked applications'], color: '#0EA5E9' },
      { id: 'grow', company: 'LMS & Interview Prep', role: 'Step 4: Prepare & Progress', period: 'Ongoing', description: 'Use courses, mock interviews, career path planning, and application tracking until offer and placement stages.', highlights: ['Mock interviews', 'Application timeline', 'Recruiter visibility'], color: '#38BDF8' },
    ],
  },
  whyHire: {
    tag: 'HR Yantra Advantage',
    title: 'Why',
    titleAccent: 'Choose HR Yantra?',
    subtitle:
      'The difference between applying everywhere and moving forward is clarity — the right profile, live portal jobs, and tracked applications from Explore Jobs to interview.',
    othersHeader: 'Other Portals',
    portalHeader: 'HR Yantra Portal',
    comparisons: [
      { others: 'Generic job boards with outdated listings', candidate: 'Live jobs from HR Yantra tenant agencies', detail: 'Explore Jobs shows current openings posted by recruiters on Phase 2 CRM.' },
      { others: 'Apply without knowing fit', candidate: 'AI match score on profile and roles', detail: 'See how your skills align before you spend time on an application.' },
      { others: 'No idea where applications stand', candidate: 'Applications hub with live status', detail: 'Track screening, assessments, interviews, and offers in one timeline.' },
      { others: 'Resume rejected by ATS silently', candidate: 'ATS Check + Resume Builder in LMS', detail: 'Improve keywords and formatting before you apply.' },
      { others: 'Unprepared for interview rounds', candidate: 'LMS mock interviews & question banks', detail: 'Practice by role, company, and skill area inside the portal.' },
      { others: 'Profile scattered across tools', candidate: 'One candidate profile for Phase 1 & 2', detail: 'Your portal profile syncs with recruiter CRM when tenants engage you.' },
    ],
    insight:
      'HR Yantra helps candidates explore live jobs, improve profiles, complete assessments, and track recruiter progress across the Phase 1 portal and agency CRM pipelines with a 94% placement rate — no guesswork, just data-driven results.',
    insightBold: 'Build a clearer profile. Find better-fit opportunities.',
  },
  cta: {
    badge: 'Join the HR Yantra candidate network',
    tagline: 'Find the job that fits you perfectly.',
    accent: 'Start on Explore Jobs.',
    subtitle:
      'Search live openings, complete your profile, apply with confidence, and track every step in Applications and your Candidate Dashboard.',
    roles: ['Technology', 'Business & Strategy', 'Finance & Banking', 'Sales & Marketing', 'HR & Operations', 'Healthcare & Education', 'Design & Customer Success'],
    exploreJobs: 'Explore Jobs',
    whatsappLogin: 'Sign in with WhatsApp',
  },
}
