import type { CandmainLandingContent } from './types'

export const candmainLandingFr: CandmainLandingContent = {
  dateLocale: 'fr-FR',
  commandCenter: {
    tag: 'Resultats de la plateforme',
    title: 'Resultats fiables.',
    titleAccent: 'Croissance de carriere mesurable.',
    subtitle:
      'Rejoignez une plateforme basee sur l\'IA concue pour aider les candidats a etre decouverts, obtenir des entretiens et accelerer leur carriere grace a la correspondance IA et a la visibilite aupres des recruteurs.',
    liveFeed: 'Fil en direct',
    ticker: [
      'Profil consulte par un recruteur - poste Operations Manager',
      'Entretien planifie - poste Analyste financier',
      'CV preselectionne - poste Coordinateur sante',
      'Qualite du profil amelioree a 94 %',
      'Nouvelle certification verifiee - Gestion de projet',
      'Evaluation de competences terminee - Communication et reporting',
      'Candidature passee en revue par le responsable du recrutement',
      'Nouvelle correspondance de poste trouvee avec 92 % d\'adequation',
      'Activite d\'offre detectee - poste Customer Success',
    ],
    stats: [
      { id: 'matches', label: 'Correspondances IA', value: '42', status: 'live', statusLabel: 'en direct', trend: 'Postes alignes sur votre profil dans Explorer les emplois.' },
      { id: 'applications', label: 'Candidatures actives', value: '18', status: 'active', statusLabel: 'actif', trend: 'Suivies dans Candidatures avec mises a jour en temps reel.' },
      { id: 'profile', label: 'Completion du profil', value: '94 %', status: 'excellent', statusLabel: 'excellent', trend: 'Completez votre profil candidat pour une meilleure visibilite recruteur.' },
      { id: 'resume', label: 'Score CV Builder', value: '88', status: 'growing', statusLabel: 'en progression', trend: 'Ameliorez la compatibilite ATS avec le CV Builder LMS.' },
      { id: 'interviews', label: 'Sessions prep. entretien', value: '12', status: 'excellent', statusLabel: 'excellent', trend: 'Entretiens simules et banques de questions dans le LMS.' },
      { id: 'ats', label: 'Taux de reussite ATS', value: '92 %', status: 'excellent', statusLabel: 'excellent', trend: 'Analysez votre CV avant de postuler aux offres ouvertes.' },
      { id: 'courses', label: 'Parcours d\'apprentissage', value: '6', status: 'active', statusLabel: 'actif', trend: 'Montez en competences avec les cours et la planification de carriere.' },
      { id: 'response', label: 'Taux de reponse recruteur', value: '58 %', status: 'growing', statusLabel: 'en progression', trend: 'Les profils plus solides obtiennent plus de reponses des recruteurs.' },
    ],
  },
  activity: {
    tag: 'Toujours en mouvement',
    title: 'Flux d\'activite',
    titleAccent: 'carriere en direct',
    subtitle:
      'Chaque consultation recruteur, mise a jour d\'entretien, preselection, correspondance de poste et signal de competence est diffuse en direct pour les candidats en tech, business, sante, finance, ventes, design, operations et plus.',
    stats: [
      { label: 'Consultations de profil', value: '42' },
      { label: 'Correspondances trouvees', value: '12,5K+' },
      { label: 'Mises a jour entretien', value: '8' },
    ],
    streamTitle: 'Flux d\'activite',
    latestUpdate: 'Derniere mise a jour',
    feed: [
      { id: 1, type: 'metrics', typeLabel: 'metriques', message: 'Candidature passee en entretien — Developpeur Full Stack', time: 'maintenant', status: 'success' },
      { id: 2, type: 'research', typeLabel: 'recherche', message: 'Recruteur a consulte votre profil — poste Product Manager', time: 'il y a 1 min', status: 'success' },
      { id: 3, type: 'accessibility', typeLabel: 'accessibilite', message: 'CV adapte pour le poste — Analyste financier', time: 'il y a 2 min', status: 'success' },
      { id: 4, type: 'product', typeLabel: 'produit', message: 'Score de correspondance IA ameliore — meilleure adequation Pune', time: 'il y a 3 min', status: 'success' },
      { id: 5, type: 'performance', typeLabel: 'performance', message: 'Evaluation preliminaire terminee — poste Operations', time: 'il y a 4 min', status: 'success' },
      { id: 6, type: 'feedback', typeLabel: 'retour', message: 'Entretien simule termine — communication renforcee', time: 'il y a 5 min', status: 'success' },
      { id: 7, type: 'deploy', typeLabel: 'deploiement', message: 'Nouvelle offre publiee — Developpeur React (Teletravail)', time: 'il y a 6 min', status: 'success' },
      { id: 8, type: 'design', typeLabel: 'design', message: 'Profil synchronise depuis le pipeline CRM Phase 2', time: 'il y a 7 min', status: 'success' },
      { id: 9, type: 'report', typeLabel: 'rapport', message: 'Rappel de suivi — candidature Sales Executive', time: 'il y a 8 min', status: 'info' },
      { id: 10, type: 'metrics', typeLabel: 'metriques', message: 'Preselectionne — vivier Customer Success', time: 'il y a 9 min', status: 'info' },
      { id: 11, type: 'research', typeLabel: 'recherche', message: 'Responsable recrutement a ouvert la candidature — HR Business Partner', time: 'il y a 10 min', status: 'success' },
      { id: 12, type: 'performance', typeLabel: 'performance', message: 'Competence ajoutee au profil — Excel et analyse business', time: 'il y a 11 min', status: 'success' },
    ],
  },
  hiring: {
    tag: 'Intelligence recrutement',
    title: 'La hierarchie complete du',
    titleAccent: 'processus de recrutement',
    subtitle:
      'Decouvrez comment les candidats passent de la candidature a l\'offre en tech, business, finance, sante, ventes, operations, design et plus.',
    funnelTitle: 'Entonnoir de recrutement en direct',
    funnelUpdated: 'Progression candidats en temps reel sur les 6 etapes - Mis a jour',
    liveData: 'Donnees en direct',
    stageLabel: 'Etape',
    liveSuffix: 'en direct',
    passPrefix: 'Reussite',
    totalPool: 'Pool total de candidats',
    refreshNote: 'Les % et compteurs en direct se mettent a jour en temps reel',
    stages: [
      { id: 'application', step: 1, title: 'Tri des CV', subtitle: 'L\'IA verifie l\'adequation du CV, les mots-cles et la correspondance au poste.', duration: '24–72 h', passRate: '~15 %', companies: ['Scan CV', 'Adequation poste', 'Profil clair'], color: '#2563EB', bg: 'rgba(37,99,235,0.06)', border: 'rgba(37,99,235,0.18)', liveCount: 12500 },
      { id: 'recruiter', step: 2, title: 'Entretien recruteur', subtitle: 'Le recruteur verifie l\'interet, la fourchette salariale et la disponibilite.', duration: '30–45 min', passRate: '~60 %', companies: ['Interet', 'Salaire', 'Disponibilite'], color: '#0EA5E9', bg: 'rgba(14,165,233,0.08)', border: 'rgba(14,165,233,0.24)', liveCount: 1875 },
      { id: 'technical', step: 3, title: 'Evaluation competences', subtitle: 'Les competences sont testees via des taches, etudes de cas ou revue de portfolio.', duration: '1–3 h', passRate: '~40 %', companies: ['Test competences', 'Etude de cas', 'Portfolio'], color: '#7C3AED', bg: 'rgba(124,58,237,0.08)', border: 'rgba(124,58,237,0.24)', liveCount: 750 },
      { id: 'hiring-manager', step: 4, title: 'Entretien manager', subtitle: 'Le manager evalue l\'experience, l\'integration equipe et l\'impact business.', duration: '45–60 min', passRate: '~55 %', companies: ['Impact', 'Equipe', 'Leadership'], color: '#F97316', bg: 'rgba(249,115,22,0.08)', border: 'rgba(249,115,22,0.24)', liveCount: 412 },
      { id: 'panel', step: 5, title: 'Entretiens panel', subtitle: 'Les tours finaux en equipe valident la coherence et la collaboration.', duration: '3–6 h', passRate: '~70 %', companies: ['Boucle equipe', 'Culture', 'Revue finale'], color: '#EC4899', bg: 'rgba(236,72,153,0.08)', border: 'rgba(236,72,153,0.24)', liveCount: 289 },
      { id: 'offer', step: 6, title: 'Offre et onboarding', subtitle: 'Offre, verification des antecedents, negociation et etapes d\'integration.', duration: '1–2 sem.', passRate: '~85 %', companies: ['Offre', 'Verification', 'Onboarding'], color: '#059669', bg: 'rgba(5,150,105,0.06)', border: 'rgba(5,150,105,0.18)', liveCount: 246 },
    ],
    banner: [
      { label: 'Delai moyen de recrutement', value: '4–8 semaines' },
      { label: 'Offres sur 12,5K+ candidatures', value: '~246 offres' },
      { label: 'Taux de reussite entretien HR Yantra', value: '94 %' },
      { label: 'Augmentation salariale via negociation', value: '+21 % moy.' },
    ],
  },
  impact: {
    tag: 'Resultats carriere',
    title: 'Le',
    titleAccent: 'tableau de bord de croissance',
    subtitle:
      'Chaque jalon de candidature, rappel recruteur, note de correspondance et metrique de conversion — suivi et mis a jour en temps reel.',
    metrics: [
      { label: 'Consultations recruteur', detail: 'Decouverte de profil en direct' },
      { label: 'Offres actives sourcees', detail: 'Postes ouverts suivis' },
      { label: 'Precision correspondance', detail: 'Validation IA profil-poste' },
      { label: 'Taux d\'entretien', detail: 'Flux candidature vers entretien' },
    ],
    chartTitle: 'Trajectoire de l\'entonnoir',
    chartUpdated: 'Vue automatique en direct - mis a jour',
    graphMeaning: 'Ce que ce graphique signifie',
    latest: 'Dernier',
    change: 'Variation',
    liveReading: 'lecture en direct',
    tabs: [
      { id: 'users', label: 'Consultations recruteur', insight: 'Frequence a laquelle les recruteurs decouvrent et ouvrent les profils candidats.', plain: 'Plus de consultations signifie une meilleure visibilite dans les recherches recruteur.' },
      { id: 'revenue', label: 'Offres actives', insight: 'Nombre de postes ouverts correspondus sur la plateforme.', plain: 'Plus d\'offres signifie plus de chances de trouver un poste pertinent.' },
      { id: 'adoption', label: 'Taux de correspondance', insight: 'Proximite entre les profils candidats et les postes disponibles.', plain: 'Un taux plus eleve signifie une meilleure adequation et moins de candidatures inutiles.' },
      { id: 'conversion', label: 'Taux d\'entretien', insight: 'Frequence a laquelle les candidats correspondants obtiennent un entretien.', plain: 'Un taux plus eleve signifie que le profil genere une traction reelle.' },
    ],
    format: { openings: 'offres', views: 'consultations' },
  },
  caseStudies: {
    tag: 'Histoires de reussite',
    title: 'Resultats simples.',
    titleAccent: 'Progression de carriere claire.',
    subtitle:
      'Decouvrez comment HR Yantra aide les candidats a explorer les emplois, ameliorer leur profil, completer les evaluations et suivre leurs candidatures via le portail Phase 1.',
    problem: 'Probleme',
    checks: 'Ce que HR Yantra verifie',
    helps: 'Comment ca aide',
    showLess: 'Voir moins',
    outcome: 'Resultat candidat',
    studies: [
      {
        id: 'explore-jobs', tag: 'Explorer les emplois', title: 'Decouvrir et postuler aux postes du portail',
        challenge: 'Les candidats naviguent entre sites d\'emploi sans savoir quelles offres sont actives, verifiees et adaptees a leur profil HR Yantra.',
        research: 'La page Explorer les emplois liste les offres en direct avec indices IA, salaire, mode de travail et candidature en un clic quand le profil est pret.',
        strategy: 'Recherchez par titre et lieu, ouvrez les details, adaptez votre CV dans le LMS et soumettez des candidatures suivies dans votre tableau de bord.',
        results: [
          { metric: 'Offres live', value: '500+', detail: 'Ouvertes sur le portail' },
          { metric: 'Score match', value: '91 %', detail: 'Adequation profil' },
          { metric: 'Candidature', value: '1 clic', detail: 'Profil pret' },
          { metric: 'Suivi', value: '100 %', detail: 'Dans Candidatures' },
        ],
        color: '#28A8E1', bgColor: 'rgba(40,168,225,0.06)',
      },
      {
        id: 'profile-lms', tag: 'Profil et LMS', title: 'Construire un profil et CV prets pour les recruteurs',
        challenge: 'Les profils incomplets et CV generiques reduisent la visibilite quand les recruteurs parcourent le pool candidats Phase 1 et CRM Phase 2.',
        research: 'HR Yantra combine Profil, Upload CV, Verification ATS et CV Builder LMS pour ameliorer mots-cles, competences et mise en forme avant de postuler.',
        strategy: 'Completez vos informations, lancez la verification ATS, utilisez l\'editeur IA et synchronisez les ameliorations sur votre dossier candidat.',
        results: [
          { metric: 'Score ATS', value: '92', detail: 'Apres optimisation' },
          { metric: 'Profil', value: '94 %', detail: 'Completion' },
          { metric: 'Competences', value: '24+', detail: 'Tags verifies' },
          { metric: 'Temps gagne', value: '8 h', detail: 'Vs edition manuelle' },
        ],
        color: '#FC9620', bgColor: 'rgba(252,150,32,0.06)',
      },
      {
        id: 'applications-pipeline', tag: 'Candidatures', title: 'Suivre chaque candidature, evaluation et entretien',
        challenge: 'Les candidats perdent le fil des tests, messages recruteur et etapes d\'entretien sur plusieurs pipelines employeurs.',
        research: 'Candidatures et Tableau de bord affichent les timelines, evaluations preliminaires, liens prep entretien et progression depuis la sync Phase 2.',
        strategy: 'Suivez les candidatures actives, completez les evaluations du flux de candidature et utilisez la prep entretien LMS avant les tours recruteur.',
        results: [
          { metric: 'Visibilite', value: '96 %', detail: 'Clarte du statut' },
          { metric: 'Evaluations', value: 'Fait', detail: 'Dans le flux' },
          { metric: 'Entretiens', value: '5', detail: 'Planifies' },
          { metric: 'Reponse', value: '58 %', detail: 'Reponses recruteur' },
        ],
        color: '#10B981', bgColor: 'rgba(16,185,129,0.06)',
      },
    ],
  },
  skills: {
    tag: 'Intelligence recrutement live',
    title: 'Ce que les recruteurs',
    titleAccent: 'recherchent',
    subtitle:
      'Les recruteurs evaluent l\'experience claire, les competences pertinentes, la communication, l\'adequation au poste, le potentiel de croissance et la preuve de valeur dans tout domaine.',
    footer:
      'Mises a jour en direct : consultations recruteur, correspondances, qualite CV, classement profil, preparation entretien, certifications, benchmarks salariaux et engagement recruteur sur la plateforme.',
    nodes: {
      center: 'Matrice d\'evaluation candidat',
      'product-strategy': 'Experience pertinente',
      'design-systems': 'Competences metier',
      'ux-research': 'Progression de carriere',
      frontend: 'Certifications',
      leadership: 'Qualite du CV',
      ai: 'Adequation au poste',
      analytics: 'Potentiel de leadership',
      accessibility: 'Communication',
      'systems-thinking': 'Resolution de problemes',
      growth: 'Impact business',
    },
  },
  experience: {
    tag: 'Parcours candidat',
    title: 'Pipeline de recrutement',
    titleAccent: 'en direct',
    subtitle:
      'Suivez le parcours d\'un candidat de la creation de profil a la decouverte recruteur, la preparation entretien et l\'elan vers l\'offre.',
    stagesCount: 'Etapes d\'evaluation en direct',
    stagesHint: 'Signal profil Etape 1 vers mouvement recrutement Etape 4',
    steps: [
      { id: 'signup', company: 'Connexion WhatsApp', role: 'Etape 1 : Rejoindre le portail', period: 'Jour 1', description: 'Connectez-vous via WhatsApp, verifiez votre numero et accedez a votre tableau de bord avec des recommandations personnalisees.', highlights: ['Connexion OTP rapide', 'Session securisee', 'Acces tableau de bord'], color: '#28A8E1' },
      { id: 'profile', company: 'Profil et CV', role: 'Etape 2 : Completer votre profil', period: 'Semaine 1', description: 'Ajoutez experience, formation, competences et uploadez votre CV. Lancez la verification ATS et ameliorez votre CV dans le LMS.', highlights: ['Profil 94 % complete', 'Optimise ATS', 'Competences taguees'], color: '#28A8DF' },
      { id: 'explore', company: 'Explorer les emplois', role: 'Etape 3 : Rechercher et postuler', period: 'Semaine 2', description: 'Parcourez les offres live des agences, filtrez par lieu et type de poste, postulez avec CV adaptes et flux de screening.', highlights: ['42 correspondances IA', 'Postes remote et hybrides', 'Candidatures suivies'], color: '#0EA5E9' },
      { id: 'grow', company: 'LMS et prep entretien', role: 'Etape 4 : Preparer et progresser', period: 'En cours', description: 'Utilisez les cours, entretiens simules, planification de carriere et suivi candidature jusqu\'aux etapes d\'offre et d\'integration.', highlights: ['Entretiens simules', 'Timeline candidature', 'Visibilite recruteur'], color: '#38BDF8' },
    ],
  },
  whyHire: {
    tag: 'Avantage HR Yantra',
    title: 'Pourquoi',
    titleAccent: 'choisir HR Yantra ?',
    subtitle:
      'La difference entre postuler partout et avancer vraiment, c\'est la clarte — le bon profil, des offres live sur le portail et des candidatures suivies de Explorer les emplois a l\'entretien.',
    othersHeader: 'Autres portails',
    portalHeader: 'Portail HR Yantra',
    comparisons: [
      { others: 'Sites d\'emploi generiques avec offres obsoletees', candidate: 'Offres live des agences HR Yantra', detail: 'Explorer les emplois affiche les postes actuels publies par les recruteurs CRM Phase 2.' },
      { others: 'Postuler sans connaitre l\'adequation', candidate: 'Score de correspondance IA sur profil et postes', detail: 'Voyez l\'alignement de vos competences avant de investir du temps.' },
      { others: 'Aucune visibilite sur les candidatures', candidate: 'Hub Candidatures avec statut en direct', detail: 'Suivez screening, evaluations, entretiens et offres sur une timeline.' },
      { others: 'CV rejete par l\'ATS sans retour', candidate: 'Verification ATS + CV Builder dans le LMS', detail: 'Ameliorez mots-cles et mise en forme avant de postuler.' },
      { others: 'Mal prepare aux entretiens', candidate: 'Entretiens simules et banques de questions LMS', detail: 'Entrainez-vous par poste, entreprise et domaine de competence.' },
      { others: 'Profil eparpille entre outils', candidate: 'Un profil candidat pour Phase 1 et 2', detail: 'Votre profil portail se synchronise avec le CRM recruteur quand les agences vous contactent.' },
    ],
    insight:
      'HR Yantra aide les candidats a explorer les offres live, ameliorer leur profil, completer les evaluations et suivre la progression recruteur sur le portail Phase 1 et les pipelines CRM agence — avec un taux de placement de 94 %, sans devinettes, avec des resultats bases sur les donnees.',
    insightBold: 'Construisez un profil plus clair. Trouvez des opportunites mieux adaptees.',
  },
  cta: {
    badge: 'Rejoignez le reseau candidats HR Yantra',
    tagline: 'Trouvez l\'emploi qui vous correspond parfaitement.',
    accent: 'Commencez sur Explorer les emplois.',
    subtitle:
      'Recherchez les offres live, completez votre profil, postulez en confiance et suivez chaque etape dans Candidatures et votre Tableau de bord candidat.',
    roles: ['Technologie', 'Business et strategie', 'Finance et banque', 'Ventes et marketing', 'RH et operations', 'Sante et education', 'Design et customer success'],
    exploreJobs: 'Explorer les emplois',
    whatsappLogin: 'Connexion avec WhatsApp',
  },
}